### PR TITLE
Play 2.8 support

### PR DESCRIPTION
**Pull request by iaco86**
Following #154:
1. Added `play-java-forms` support to 2.8.x in `PlayApplicationPlugin`
2. Created new `PlayTwirlAdapterV28X` based on [Play 2.8 TemplateImports.java](https://github.com/playframework/playframework/blob/2.8.x/dev-mode/build-link/src/main/java/play/TemplateImports.java)

Tests seem to be passing locally.

### CODE REVIEW

**Comment by iaco86** [comment]
@JLLeitschuh let me know if there's anything else I need to do to start with this review, first time contributing to the project for me :)

**Comment by JLLeitschuh** [comment]
It looks like this is indeed passing all the tests. Really nice work! I'm going to give some others an opportunity to review/provide feedback. I'll merge this Tuesday if I don't hear any other concerns.

**Review by JLLeitschuh — APPROVED** [review]
LGTM!

**Comment by iaco86** [comment]
@JLLeitschuh I was able to build and test the updated plugin from my branch with a project running the latest play 2.8.7 and it worked fine!
Looking forward to be able to use the new version!

**Comment by iaco86** [comment]
@JLLeitschuh any chance this can be merged this week?
Thanks!

**Comment by JLLeitschuh** [comment]
@big-guy has asked us to hold off on merging this change until after 7.0 is released.

**Comment by arkangelboss-github** [comment]
> @big-guy has asked us to hold off on merging this change until after 7.0 is released.

Hi @JLLeitschuh, I would love to see a minor version of the project released even before that if it does not create too much work. 

I am looking at migrating a project to Play 2.8.7 from 2.7.9 since we are about end of life (https://discuss.lightbend.com/t/end-of-support-roadmap/7619/2) and to also take care of some dependencies (like some of the jackson libs) and their CVEs without resorting to manually forcing versions.

**Comment by iaco86** [comment]
@JLLeitschuh @big-guy same problem here - is there an ETA that you could share for when this could be merged? 
Also, do you foresee issues with this plugin compatibility with gradle 7?

We are not planning to upgrade to gradle 7 anytime soon, and am worried, if this plugin turns out to be incompatible with gradle 7, this change will end up not being merged and we'll have to find a workaround to update to play 2.8.x.

Thanks!

**Comment by JLLeitschuh** [comment]
I see no issues merging this. I'm fully in support of moving this forward.

**Comment by JLLeitschuh** [comment]
@iaco86 thank you so much for finally pushing this over the finish line. I really appreciate it!

**Comment by iaco86** [comment]
@JLLeitschuh No problem! I'm glad I could help - thanks for maintaining support despite this being a not-so-popular plugin.
Looking forward for the plugin release!

**Pull request merged**
