### PR TITLE
Replace deprecated usage of AbstractArchiveTask.getBaseName & Abstrac…

### PR DESCRIPTION
**Pull request by PaulFridrick**
This code fixes a Gradle 6 warning, see issue #114

### CODE REVIEW

**Comment by JLLeitschuh** [comment]
I believe this may break compatibility with Gradle 5.1.1?

**Comment by PaulFridrick** [comment]
Hi,
All tests are green on my side. From what I understand v5.1.1 of Gradle is included in the auto tests, so I believe this PR is not breaking compatibility.
Cheers

**Comment by cstroe** [comment]
@PaulFridrick can you merge master into your branch?  We recently fixed the CI build and we should be able to see all the tests on your PR pass.

**Comment by JLLeitschuh** [comment]
Also, please sign off on your commits to make it so that DCO passes.

**Pull request closed without merging**
