### PR TITLE
Gradle 6 migration

### PR DESCRIPTION
**Pull request by PaulFridrick**
I changed the gradle wrapper version to 6.0.1, and I adapted the gradle conf files and fixed some tests accordingly

### CODE REVIEW

**Comment by JLLeitschuh** [comment]
Hi @PaulFridrick,

Please either check 'Allow edits from maintainers.' or update this branch to be in sync with `master`.

Cheers,
Jonathan Leitschuh

**Comment by PaulFridrick** [comment]
It looks checked on my side (see the screenshot), did I miss something ?

image

**Comment by JLLeitschuh** [comment]
Huh, well the button is just broken on my end... if you wouldn't mind, I'd appreciate if you performed the sync for us.

**Comment by benmccann** [comment]
@PaulFridrick would you be able to rebase this PR?

**Comment by PaulFridrick** [comment]
Done ! I also updated the gradle wrapper to 6.3.

Cheers

**Comment by JLLeitschuh** [comment]
Thanks @PaulFridrick for your contribution!

**Pull request merged**
