### PR TITLE
#142: Remove 2.3 and pre-5 from Docs and Test Coverage

### PR DESCRIPTION
**Pull request by marracuene**
Part of Fix for #142 .
Includes setting maxParallelForks to 1 in order to facilitate investigation of CI build failures.

### CODE REVIEW

**Comment by JLLeitschuh** [comment]
Hey @marracuene I think that the issue you were attempting to solve has been fixed by @cstroe? Is this accurate?

**Comment by marracuene** [comment]
> Hey @marracuene I think that the issue you were attempting to solve has been fixed by @cstroe? Is this accurate?

Hi @JLLeitschuh I agree that https://github.com/gradle/playframework/pull/147 by @cstroe maxes this PR obsolete.   However please note that there he skipped several tests for 2.3, in order to get the build working.   Therefore you might want to update the docs to mention that 2.3 support might be patchy?

**Comment by JLLeitschuh** [comment]
I think we may have dropped support for 2.3 somewhere. I don't remember. Sorry.

**Comment by cstroe** [comment]
The tests that were skipped did not seem to apply to version 2.3.  There were many other tests that run with version 2.3, so there is coverage left for that version.  I can definitely understand if the decision is made to drop support for 2.3, so don't let me stop you, but that should probably be a new PR.

I tried to document the tests that did not apply to version 2.3.

**Pull request closed without merging**
