### PR TITLE
Reset idea dependencies to avoid compiling all sources

### PR DESCRIPTION
**Pull request by JospehChiu**
The issue is described in #144 that running `./gradlew idea` will compile all sources. Tests are covered in [PlayIdeaPluginBasicIntegrationTest](https://github.com/gradle/playframework/blob/95e68fe1a90dc40b9ce8b704e1c902369a67490c/src/integTest/groovy/org/gradle/playframework/application/basic/PlayIdeaPluginBasicIntegrationTest.groovy).

### CODE REVIEW

**Comment by ymwang1984** [comment]
@big-guy I wonder if this can be reviewed. Thank you.

**Comment by JLLeitschuh** [comment]
Would you be so kind as to provide an integration test for this behaviour?

**Comment by JospehChiu** [comment]
It's really great that it already has integration test to make sure code generation tasks are run in [PlayIdeaPluginIntegrationTest](https://github.com/gradle/playframework/blob/ccfb7a0b6b939cac504243c335256687567a3011/src/integTest/groovy/org/gradle/playframework/application/PlayIdeaPluginIntegrationTest.groovy#L128).
```
def "IDEA plugin depends on source generation tasks"() {
        applyIdePlugin()

        when:
        BuildResult result = build(ideTask)
        then:
        buildTasks.each {
            assert result.task(it).outcome == TaskOutcome.SUCCESS
        }
    }
```

and list of build tasks is declared at [PlayIdeaPluginBasicIntegrationTest](https://github.com/gradle/playframework/blob/95e68fe1a90dc40b9ce8b704e1c902369a67490c/src/integTest/groovy/org/gradle/playframework/application/basic/PlayIdeaPluginBasicIntegrationTest.groovy#L37) that includes `ROUTES_COMPILE_TASK_NAME ` and `TWIRL_COMPILE_TASK_NAME `.
```
String[] getBuildTasks() {
        [
            ROUTES_COMPILE_TASK_PATH,
            TWIRL_COMPILE_TASK_PATH,
            ":ideaProject",
            ":ideaModule",
            ":ideaWorkspace",
            ":idea"
        ]
    }
```

**Comment by JLLeitschuh** [comment]
I guess the assertion here that we'd be looking to add is a test that verifies that certain tasks are not being executed? Correct?

**Comment by JospehChiu** [comment]
Hi @JLLeitschuh, could you check the modification in integration tests when you are available?

**Review by JLLeitschuh — APPROVED** [review]
Looks good to me! Thanks!

**Comment by ymwang1984** [comment]
Thank you @JLLeitschuh 
Please let us know when we could cut a release 0.10.

**Comment by JLLeitschuh** [comment]
This will require someone from the community contributing a PR to automate the process of performing a release. Ideally something with GitHub actions. If someone can contribute this, I'll add the credentials to the repository so we can use them.

**Comment by ymwang1984** [comment]
Got it, thank you. I saw Gradle repo has github actions. Can we use that?

**Comment by JLLeitschuh** [comment]
This repo supports running GitHub actions as well. Just need someone to create a PR with the required actions file.

**Comment by ymwang1984** [comment]
Cool. Where do we publish to? MavenCentral? Or the Gradle plugin portal?

**Comment by JLLeitschuh** [comment]
Gradle plugin portal. See the project README

**Comment by ymwang1984** [comment]
sounds good

https://github.com/gradle/playframework/pull/152

**Pull request merged**
