### PR TITLE
Issue #83 - [platform-play] TwirlCompiler support for dependency inje…

### PR DESCRIPTION
**Pull request by cmsr**
Signed-off-by: Carlos Rodrigues <cmsrodrigues@gmail.com>

### Context
Allows support for Twirl templates with dependency injection.

### Contributor Checklist
- [x] [Review Contribution Guidelines](https://github.com/gradle/gradle/blob/master/CONTRIBUTING.md)
- [x] Make sure that all commits are [signed off](https://git-scm.com/docs/git-commit#git-commit---signoff) to indicate that you agree to the terms of [Developer Certificate of Origin](https://developercertificate.org/).
- [x] Check ["Allow edit from maintainers" option](https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/) in pull request so that additional changes can be pushed by Gradle team
- [x] Provide integration tests (under `src/integTest`) to verify changes from a user perspective
- [ ] Provide unit tests (under `src/test`) to verify logic
- [x] Update User Guide, DSL Reference, and Javadoc for public-facing changes
- [ ] Ensure that tests pass locally: `./gradlew check`

### Gradle Core Team Checklist
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation
- [ ] Recognize contributor in release notes

### CODE REVIEW

**Comment by cmsr** [comment]
@big-guy is there any update on this request?

**Comment by cmsr** [comment]
@ldaley @pledbrook @hansd @timyates I'm sorry guys to be annoying, but is there any evolution for this request?

**Comment by big-guy** [comment]
Thanks @cmsr - hope to put out a 0.10 next week with these fixes.

**Comment by luispmenezes** [comment]
> Thanks @cmsr - hope to put out a 0.10 next week with these fixes.

Any estimation on when 0.10 will be released?

**Comment by JLLeitschuh** [comment]
@cmsr thanks for doing this, I just needed this exact feature. I really appreciate your having contributed it

**Pull request merged**
