### PR TITLE
bump up integration test version to Play 2.7.5

### PR DESCRIPTION
**Pull request by cstroe**
This PR hopes to move along the progress on #92
* Bump up integration tests to run with the latest version of Play 2.7.x (2.7.5)
* Minor update to docs to mention 2.7.x support

### CODE REVIEW

**Comment by cstroe** [comment]
Seems like there is no version 2.7.5 of the routes compiler (see [jcenter](https://jcenter.bintray.com/com/typesafe/play/routes-compiler_2.13)).

@JLLeitschuh how do we typically get routes_compiler to be published to JCenter?

**Comment by JLLeitschuh** [comment]
> @JLLeitschuh how do we typically get routes_compiler to be published to JCenter?

Honestly, I have absolutely no idea.

I'm assuming that this is automatically tested correct? Looks like some of the CI tests are failing, can you provide insights there?

**Comment by cstroe** [comment]
The tests on this PR are failing because of this: https://github.com/gradle/playframework/blob/423796bbc15d278fc8710331e48de1c8287ddb06/src/main/java/org/gradle/playframework/tools/internal/routes/DefaultVersionedRoutesCompilerAdapter.java#L21

The class expects the com.typesafe.play:routes-compiler dependency to be available with the matching Play version.  That's why I was asking how the dependency is published.  Seems to be from the [Play repository](https://github.com/playframework/playframework/tree/master/dev-mode/routes-compiler/src).

**Comment by cstroe** [comment]
Seems like there was an issue with publishing versions 2.7.4 and 2.7.5 of the Play routes compiler for Scala 2.13: https://github.com/playframework/playframework/issues/10333

**Comment by cstroe** [comment]
@JLLeitschuh would you have time to take a look at this PR?

**Review by JLLeitschuh — APPROVED** [review]
Looks good to me!

**Pull request merged**
